import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createCommunityServer} from '../server/community-server.mjs';

const payload=(id='w1')=>({workoutId:id,idempotencyKey:id,workoutDate:'2026-10-01',exerciseCount:1,completedSetCount:1,comment:'좋았어요',visibility:{names:false,weights:false,reps:false}});
async function fixture(options={}){const {server,purge}=createCommunityServer({environment:'development',allowDevAuth:true,dbPath:':memory:',adminToken:'admin-secret',callbackBasicAuth:'callback-secret',...options});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const base=`http://127.0.0.1:${server.address().port}/api/community`;return {purge,close:()=>new Promise(resolve=>server.close(resolve)),async request(path,method='GET',body,token){const response=await fetch(base+path,{method,headers:{...(body?{'Content-Type':'application/json'}:{}),...(token?{Authorization:`Bearer ${token}`}:{})},body:body?JSON.stringify(body):undefined});return {status:response.status,...await response.json()};},base};}
async function login(f,name){const session=await f.request('/auth/dev','POST',{identity:name});assert.equal(session.status,200);await f.request('/me','PATCH',{nickname:name,rulesAccepted:true},session.token);return session;}

test('authorization, privacy, desired cheers, reports, blocks and withdrawal',async()=>{const f=await fixture();try{const a=await login(f,'운동가'),b=await login(f,'응원가');assert.equal((await f.request('/posts','POST',payload())).status,401);const result=await f.request('/posts','POST',payload(),a.token);assert.equal(result.status,201);const id=result.post.id;assert.equal((await f.request('/posts/'+id,'DELETE',{},b.token)).status,403);assert.equal((await f.request('/posts/'+id+'/cheer','PUT',{active:true},a.token)).status,403);await f.request('/posts/'+id+'/cheer','PUT',{active:true},b.token);assert.equal((await f.request('/posts/'+id+'/cheer','PUT',{active:true},b.token)).post.cheerCount,1);const publicPost=(await f.request('/feed')).posts[0];assert.equal(publicPost.workoutId,undefined);assert.equal(publicPost.exercises.length,0);assert.equal(JSON.stringify(publicPost).includes('subject'),false);await f.request('/blocks/'+a.user.id,'PUT',{active:true},b.token);assert.equal((await f.request('/feed','GET',undefined,b.token)).posts.length,0);await f.request('/blocks/'+a.user.id,'PUT',{active:false},b.token);await f.request('/posts/'+id+'/report','POST',{reason:'privacy'},b.token);assert.equal((await f.request('/posts/'+id+'/report','POST',{reason:'privacy'},b.token)).status,200);assert.equal((await f.request('/feed','GET',undefined,b.token)).posts.length,0);assert.equal((await f.request('/feed')).posts.length,1);assert.equal((await f.request('/admin/reports')).status,403);await f.request('/admin/posts/'+id,'PATCH',{hidden:true},'admin-secret');assert.equal((await f.request('/feed')).posts.length,0);await f.request('/admin/posts/'+id,'PATCH',{hidden:false},'admin-secret');await f.request('/me','DELETE',{},a.token);assert.equal((await f.request('/feed')).posts.length,0);assert.equal((await f.request('/me','GET',undefined,a.token)).status,401);const report=(await f.request('/admin/reports','GET',undefined,'admin-secret')).reports[0];assert.equal(report.post,null);assert.equal(report.snapshot,null);}finally{await f.close();}});

test('concurrent retry unique workout, payload privacy, graphemes, expiration',async()=>{let now=1000;const f=await fixture({now:()=>now,sessionTtlMs:10000});try{const a=await login(f,'운동가');const results=await Promise.all(Array.from({length:8},()=>f.request('/posts','POST',payload(),a.token)));assert.equal(new Set(results.map(r=>r.post.id)).size,1);assert.equal((await f.request('/posts','POST',{...payload(),idempotencyKey:'another'},a.token)).duplicate,true);assert.equal((await f.request('/posts','POST',{...payload(),comment:'changed'},a.token)).status,409);assert.equal((await f.request('/posts','POST',{...payload('private'),note:'secret'},a.token)).status,400);assert.equal((await f.request('/posts','POST',{...payload('private'),exercises:[{name:'secret'}]},a.token)).status,400);assert.equal((await f.request('/posts','POST',{...payload('emoji'),comment:'👨‍👩‍👧‍👦'.repeat(100)},a.token)).status,201);assert.equal((await f.request('/posts','POST',{...payload('long'),comment:'👨‍👩‍👧‍👦'.repeat(101)},a.token)).status,400);assert.equal((await f.request('/posts','POST',{...payload('date'),workoutDate:'2026-02-30'},a.token)).status,400);assert.equal((await f.request('/me','PATCH',{nickname:'a',rulesAccepted:true},a.token)).status,400);now=12000;assert.equal((await f.request('/me','GET',undefined,a.token)).error.code,'AUTH_EXPIRED');}finally{await f.close();}});

test('public cursor 20, persistence and account-scoped workout uniqueness',async()=>{const directory=mkdtempSync(join(tmpdir(),'community-'));const dbPath=join(directory,'db.sqlite');let f=await fixture({dbPath});try{const a=await login(f,'운동가'),b=await login(f,'응원가');for(let i=0;i<10;i++)await f.request('/posts','POST',payload('a'+i),a.token);for(let i=0;i<10;i++)await f.request('/posts','POST',payload('b'+i),b.token);const c=await login(f,'다음가');await f.request('/posts','POST',payload('a1'),c.token);const first=await f.request('/feed');assert.equal(first.posts.length,20);assert.ok(first.nextCursor);const second=await f.request('/feed?cursor='+first.nextCursor);assert.equal(second.posts.length,1);assert.ok(!first.posts.some(p=>p.id===second.posts[0].id));await f.close();f=await fixture({dbPath});assert.equal((await f.request('/feed')).posts.length,20);assert.equal((await f.request('/me','GET',undefined,a.token)).status,200);}finally{await f.close();rmSync(directory,{recursive:true,force:true});}});

test('production refuses dev auth, trusted verifier and authenticated withdrawal callback',async()=>{const f=await fixture({environment:'production',authVerifier:{verify:async()=>({subject:'123',identityKind:'toss'})}});try{assert.equal((await f.request('/auth/dev','POST',{identity:'any'})).status,403);assert.equal((await f.request('/auth/toss','POST',{authorizationCode:'a',referrer:'SANDBOX'})).status,403);const a=await f.request('/auth/toss','POST',{authorizationCode:'a',referrer:'DEFAULT'});assert.equal(a.status,200);assert.equal((await f.request('/auth/toss','POST',{authorizationCode:'a',referrer:'DEFAULT',userId:'fake'})).status,400);assert.equal((await f.request('/auth/withdrawal-callback','POST',{userKey:123})).status,401);const response=await fetch(f.base+'/auth/withdrawal-callback',{method:'POST',headers:{Authorization:'Basic callback-secret','Content-Type':'application/json'},body:JSON.stringify({userKey:123,referrer:'UNLINK'})});assert.equal(response.status,200);assert.equal((await f.request('/me','GET',undefined,a.token)).status,401);const probe=await fetch(f.base+'/auth/withdrawal-callback?userKey=0',{headers:{Authorization:'Basic callback-secret'}});assert.equal(probe.status,200);}finally{await f.close();}const noAuth=await fixture({environment:'production'});try{assert.equal((await noAuth.request('/auth/toss','POST',{authorizationCode:'a',referrer:'DEFAULT'})).status,503);}finally{await noAuth.close();}});

test('report retention keeps personal hiding, moderator restriction permits erasure, hidden retries reject',async()=>{let now=1000;const f=await fixture({now:()=>now,sessionTtlMs:100*86400000});try{const a=await login(f,'운동가'),b=await login(f,'응원가');const post=(await f.request('/posts','POST',payload(),a.token)).post;await f.request('/posts/'+post.id+'/report','POST',{reason:'other'},b.token);now+=31*86400000;f.purge();assert.equal((await f.request('/admin/reports','GET',undefined,'admin-secret')).reports.length,0);assert.equal((await f.request('/feed','GET',undefined,b.token)).posts.length,0);await f.request('/admin/posts/'+post.id,'PATCH',{hidden:true},'admin-secret');assert.equal((await f.request('/posts','POST',payload(),a.token)).error.code,'POST_HIDDEN');assert.equal((await f.request('/posts','POST',{...payload(),idempotencyKey:'newkey'},a.token)).error.code,'POST_HIDDEN');await f.request('/admin/users/'+a.user.id,'PATCH',{restricted:true},'admin-secret');assert.equal((await f.request('/me','GET',undefined,a.token)).status,200);assert.equal((await f.request('/posts','POST',payload('w2'),a.token)).status,403);assert.equal((await f.request('/me','DELETE',{},a.token)).status,200);}finally{await f.close();}});

test('selective snapshots never accept hidden fields and policy CORS stays explicit',async()=>{const f=await fixture({allowedOrigins:['http://127.0.0.1:5193']});try{const a=await login(f,'운동가');const body={...payload(),visibility:{names:true,weights:true,reps:false},exercises:[{name:'스쿼트',sets:[{weight:60}]}]};assert.equal((await f.request('/posts','POST',body,a.token)).status,201);assert.equal((await f.request('/posts','POST',{...body,workoutId:'w2',idempotencyKey:'w2',exercises:[{name:'스쿼트',sets:[{weight:60,reps:8}]}]},a.token)).error.code,'PRIVATE_FIELD');const policy=await fetch(f.base+'/policy',{headers:{Origin:'http://127.0.0.1:5193'}});assert.equal(policy.headers.get('Access-Control-Allow-Origin'),'http://127.0.0.1:5193');assert.equal((await fetch(f.base+'/policy',{headers:{Origin:'https://evil.example'}})).status,403);}finally{await f.close();}});
